### ISSUE TITLE
screw size for mounting

### ISSUE THREAD

**Issue by BlackNet** [3DAixperts/skirt-button-pcb#4]
Have one of these boards.  What size screws does it take to mount to the printed skirt frame?

**Comment by Markus-1984** [comment]
The screws are M2x6 self tapping and included.

**Comment by 3DAixperts** [comment]
The screws are M2x6 self tapping and are included in the set.

**Comment by BlackNet** [comment]
ok, thanks.  didn't see it listed anywhere and was not sure what size.  will close this and thanks for the reply and info.
